const movies = [
  {
    id: 1,
    title: "Inception",
    director: "Christopher Nolan",
    rating: 8.8,
    released: " 15 July 2010",
    runtime: "2h 28min",
    genre: "Action, Adventure, Sci-Fi",
    plot: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    poster:
      "https://lh3.googleusercontent.com/proxy/VMJlwK72I_7X8BIwI2hAJ3jWBgDMO-1HPLbzGO8Nf-FJ7iHw7Wx7YAtNCDU35cdg2_1wq1uMEl2yxCNbVBmgovXNNJivWapNI5z4",
  },
  {
    id: 2,
    title: "Interstellar",
    director: "Christopher Nolan",
    rating: 8.6,
    released: "26 October 2014",
    runtime: "2h 49min",
    genre: "Adventure, Dram, Sci-Fi",
    plot: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    poster: "https://i.pinimg.com/originals/c6/d4/e2/c6d4e2803a467b99ede238fee57441a7.jpg",
  },
  {
    id: 3,
    title: "Good Will Hunting",
    director: "Gus Van Sant",
    rating: 8.3,
    released: "5 August 1998",
    runtime: "2h 6min",
    genre: "Drama, Romance",
    plot: "Will Hunting, a janitor at M.I.T., has a gift for mathematics, but needs help from a psychologist to find direction in his life.",
    poster: "https://images-na.ssl-images-amazon.com/images/I/610kKP6roBL._AC_SY606_.jpg",
  },
  {
    id: 4,
    title: "The Prestige",
    director: "Christopher Nolan",
    rating: 8.5,
    released: "14 February 2007",
    runtime: "2h 10min",
    genre: "Drama, Mystery, Sci-Fi",
    plot: "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
    poster: "https://i.pinimg.com/736x/35/66/3b/35663bd80d174c1f251d9d1d3f793b9c.jpg",
  },
  {
    id: 5,
    title: "A Quiet Place",
    director: "John Krasinski",
    rating: 7.5,
    released: "9 March 2018",
    runtime: "1h 30min",
    genre: "Drama, Horror, Sci-Fi",
    plot: "In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.",
    poster: "https://m.media-amazon.com/images/M/MV5BMjI0MDMzNTQ0M15BMl5BanBnXkFtZTgwMTM5NzM3NDM@._V1_.jpg",
  },
  {
    id: 6,
    title: "The Pursuit of Happyness",
    director: "Gabriele Muccino",
    rating: 8,
    released: "7 February 2007",
    runtime: "1h 57min",
    genre: "Biography, Drama",
    plot: "A struggling salesman takes custody of his son as he's poised to begin a life-changing professional career.",
    poster: "https://images-na.ssl-images-amazon.com/images/I/41AoisVN16L._AC_.jpg",
  },
  {
    id: 7,
    title: "Tenet",
    director: "Gabriele Muccino",
    rating: 7.4,
    released: "26 August 2020",
    runtime: "2h 30min",
    genre: "Action, Sci-Fi, Thriller",
    plot: "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
    poster: "https://cdn.shopify.com/s/files/1/0057/3728/3618/products/tenet2020.ar_480x.progressive.jpg?v=1578062934",
  },
  {
    id: 8,
    title: "A Separation",
    director: "Asghar Farhadi",
    rating: 8.3,
    released: "28 June 2012",
    runtime: "2h 3min",
    genre: "Drama",
    plot: "A married couple are faced with a difficult decision - to improve the life of their child by moving to another country or to stay in Iran and look after a deteriorating parent who has Alzheimer's disease.",
    poster: "https://m.media-amazon.com/images/M/MV5BZDRiZDY2YmEtZjMzNi00YTM4LWJkMmItYjFkNTQxMjQxNjA4XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SY1000_CR0,0,690,1000_AL_.jpg",
  },
];

export default movies;